# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just Meat
email: michael@bitstein.org
description: >-
  Carnivorous eating, paleolithic ketogenic diet and medicine, and zero carb
  lifestyle. Donâ€™t bother with vegetables. Just eat meat.
baseurl: ""
url: "https://justmeat.co"
twitter_username: bitstein
github_username:  bitstein

markdown: kramdown

collections:
  peoples:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: "wiki/pages"
      type: "pages"
    values:
      layout: wiki-page
      permalink: /wiki/:basename/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bin
